export const Cities = [
  { city: 'Tbilisi', temperature: 25 },
  { city: 'Madrid', temperature: 30 },
  { city: 'Berlin', temperature: 28 },
  { city: 'Paris', temperature: 32 },
  { city: 'Ottawa', temperature: 20 },
  { city: 'Washington', temperature: 22 },
  { city: 'Brussels', temperature: 25 },
  { city: 'Tokyo', temperature: 27 },
  { city: 'Beijing', temperature: 23 },
  { city: 'Lisbon', temperature: 30 },
  { city: 'Buenos Aires', temperature: 29 },
  { city: 'Moscow', temperature: 17 },
  { city: 'Stockholm', temperature: 15 },
  { city: 'Cairo', temperature: 35 },
  { city: 'Athens', temperature: 25 },
  { city: 'Reykjavik', temperature: 13 },
];
